sudo: required

language: go
go:
  - "1.9"

services:
      - docker

addons:
  apt:
    packages:
      - docker-ce

script:
    - sh build.sh


after_success:
    - if [ ! -s "$TRAVIS_TAG" ] ; then 
        echo "Time to tag images as $TRAVIS_TAG and push remote"
      fi