sudo: required

language: go

go:
  - "1.9.x"

services:
      - docker

addons:
  apt:
    packages:
      - docker-ce

script:
    - make build

after_success:
    - if [ -z $TAG ]; then
        if [ -z $NAMESPACE ]; then
          export $NAMESPACE=functions
        fi;

        echo $DOCKER_PASSWORD | docker login -u=$DOCKER_USERNAME --password-stdin;
        docker push $NAMESPACE/kafka-connector:$TAG;

      fi;